//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUBE.PAYROLL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterEmployee
    {
        public int Id { get; set; }
        public Nullable<int> MembershipNo { get; set; }
        public string EmployeeName { get; set; }
        public string FatherName { get; set; }
        public string ShortName { get; set; }
        public string Gender { get; set; }
        public string NRIC { get; set; }
        public string BloodGroup { get; set; }
        public Nullable<int> BankId { get; set; }
        public Nullable<int> BankBranchId { get; set; }
        public Nullable<int> PositionId { get; set; }
        public Nullable<int> RaceId { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> DateOfJoining { get; set; }
        public string IdentyMark { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public Nullable<int> CityId { get; set; }
        public string MobileNo { get; set; }
        public string TelephoneNo { get; set; }
        public string Email { get; set; }
        public string GSTNo { get; set; }
        public string BankAccountNo { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public Nullable<decimal> POB { get; set; }
        public Nullable<decimal> NEC { get; set; }
        public Nullable<decimal> SECONDMENT { get; set; }
        public Nullable<decimal> SPECIAL { get; set; }
        public Nullable<decimal> COLA { get; set; }
        public Nullable<bool> IsOverTimeEligible { get; set; }
        public Nullable<bool> EPFContributionRate { get; set; }
        public Nullable<bool> EPFContribution { get; set; }
        public Nullable<bool> SOCSOContribution { get; set; }
        public Nullable<decimal> KOPERASI { get; set; }
        public Nullable<bool> NubeSubscription { get; set; }
        public Nullable<decimal> GMIS { get; set; }
        public Nullable<decimal> BIMBLoan { get; set; }
        public Nullable<decimal> GELA { get; set; }
        public Nullable<decimal> HomeCarLoans { get; set; }
        public Nullable<decimal> PCB { get; set; }
        public Nullable<decimal> UnpaidLeave { get; set; }
        public Nullable<bool> IsOtherEligible { get; set; }
        public Nullable<decimal> Others { get; set; }
        public Nullable<bool> RatioOfContribution { get; set; }
        public Nullable<bool> EPF { get; set; }
        public Nullable<bool> SOCSO { get; set; }
    
        public virtual MasterBank MasterBank { get; set; }
        public virtual MasterBankBranch MasterBankBranch { get; set; }
        public virtual MasterCity MasterCity { get; set; }
        public virtual MasterPosition MasterPosition { get; set; }
        public virtual MasterRace MasterRace { get; set; }
    }
}
