//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUBE.PAYROLL.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PayrollEntities : DbContext
    {
        public PayrollEntities()
            : base("name=PayrollEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CompanyDetail> CompanyDetails { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<EntityType> EntityTypes { get; set; }
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<LogDetail> LogDetails { get; set; }
        public virtual DbSet<LogDetailType> LogDetailTypes { get; set; }
        public virtual DbSet<LogMaster> LogMasters { get; set; }
        public virtual DbSet<MasterBank> MasterBanks { get; set; }
        public virtual DbSet<MasterBankBranch> MasterBankBranches { get; set; }
        public virtual DbSet<MasterCity> MasterCities { get; set; }
        public virtual DbSet<MasterCountry> MasterCountries { get; set; }
        public virtual DbSet<MasterEmployee> MasterEmployees { get; set; }
        public virtual DbSet<MasterNubeBranch> MasterNubeBranches { get; set; }
        public virtual DbSet<MasterPosition> MasterPositions { get; set; }
        public virtual DbSet<MasterRace> MasterRaces { get; set; }
        public virtual DbSet<MasterState> MasterStates { get; set; }
        public virtual DbSet<UserTypeDetail> UserTypeDetails { get; set; }
        public virtual DbSet<UserTypeFormDetail> UserTypeFormDetails { get; set; }
        public virtual DbSet<ViewMasterbankbranch> ViewMasterbankbranches { get; set; }
        public virtual DbSet<ViewMasterCity> ViewMasterCities { get; set; }
        public virtual DbSet<ViewMasterState> ViewMasterStates { get; set; }
        public virtual DbSet<UserAccount> UserAccounts { get; set; }
    }
}
