//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUBE.PAYROLL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewMasterbankbranch
    {
        public int Id { get; set; }
        public string BankBranchName { get; set; }
        public string UserCode { get; set; }
        public Nullable<int> BankId { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public Nullable<int> CityId { get; set; }
        public string ZipCode { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Email { get; set; }
        public Nullable<int> NubeBranchId { get; set; }
        public Nullable<bool> IsHeadQuarters { get; set; }
        public string BankName { get; set; }
        public string NubeBranchName { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CountryId { get; set; }
    }
}
