//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUBE.PAYROLL.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceCorrection
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> BeforeInTime { get; set; }
        public Nullable<System.DateTime> BeforeOutTime { get; set; }
        public Nullable<System.DateTime> BeforeOtInTime { get; set; }
        public Nullable<System.DateTime> BeforeOtOutTime { get; set; }
        public Nullable<System.DateTime> AfterInTime { get; set; }
        public Nullable<System.DateTime> AfterOutTime { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual MasterEmployee MasterEmployee { get; set; }
    }
}
