//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUBE.PAYROLL.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyAttedanceDet
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<System.DateTime> AttDate { get; set; }
        public Nullable<System.DateTime> InTime { get; set; }
        public Nullable<System.DateTime> OutTime { get; set; }
        public Nullable<System.TimeSpan> TotalWorkingHours { get; set; }
        public bool WithPermission { get; set; }
        public Nullable<System.TimeSpan> OTHours { get; set; }
        public string Remarks { get; set; }
        public bool IsFullDayLeave { get; set; }
        public bool IsHalfDayLeave { get; set; }
        public bool IsWeekOff { get; set; }
        public bool IsPublicHoliday { get; set; }
        public bool IsModified { get; set; }
    
        public virtual MasterEmployee MasterEmployee { get; set; }
    }
}
