//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUBE.PAYROLL.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeIncrement
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<decimal> IncrementProposal { get; set; }
        public Nullable<decimal> CurrenttSalary { get; set; }
        public Nullable<decimal> NewSalary { get; set; }
        public int PositionId { get; set; }
        public Nullable<System.DateTime> WithEffectFrom { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public int ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual MasterEmployee MasterEmployee { get; set; }
        public virtual MasterEmployee MasterEmployee1 { get; set; }
        public virtual MasterEmployee MasterEmployee2 { get; set; }
        public virtual MasterPosition MasterPosition { get; set; }
    }
}
