//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUBE.PAYROLL.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanPayment
    {
        public decimal id { get; set; }
        public Nullable<decimal> Employeeid { get; set; }
        public string LoanName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    }
}
