//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUBE.PAYROLL.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManualOTEntry
    {
        public int Id { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<decimal> TotalOtHours { get; set; }
        public Nullable<decimal> TotalOtAmount { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string Remarks { get; set; }
    }
}
