//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUBE.PAYROLL.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterEmployee()
        {
            this.AttedanceLogs = new HashSet<AttedanceLog>();
            this.AttendanceCorrections = new HashSet<AttendanceCorrection>();
            this.DailyAttedanceDets = new HashSet<DailyAttedanceDet>();
            this.DailyLateLogs = new HashSet<DailyLateLog>();
            this.LatePermissionDetails = new HashSet<LatePermissionDetail>();
            this.LeavePermissionDetails = new HashSet<LeavePermissionDetail>();
            this.OTClaims = new HashSet<OTClaim>();
            this.OverTimeDetails = new HashSet<OverTimeDetail>();
            this.PCBs = new HashSet<PCB>();
            this.TempAttendanceTimings = new HashSet<TempAttendanceTiming>();
            this.YearlyAllowances = new HashSet<YearlyAllowance>();
            this.MonthlyDeductions = new HashSet<MonthlyDeduction>();
            this.MonthlySalaries = new HashSet<MonthlySalary>();
        }
    
        public int Id { get; set; }
        public Nullable<int> MembershipNo { get; set; }
        public string EmployeeName { get; set; }
        public string FatherName { get; set; }
        public string ShortName { get; set; }
        public string Gender { get; set; }
        public string NRIC { get; set; }
        public string BloodGroup { get; set; }
        public Nullable<int> BankId { get; set; }
        public Nullable<int> NubeBranchId { get; set; }
        public Nullable<int> PositionId { get; set; }
        public Nullable<int> RaceId { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> DateOfJoining { get; set; }
        public string IdentyMark { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public Nullable<int> CityId { get; set; }
        public string MobileNo { get; set; }
        public string TelephoneNo { get; set; }
        public string EmergencyNo { get; set; }
        public string Email { get; set; }
        public string GSTNo { get; set; }
        public string BankAccountNo { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public Nullable<decimal> POB { get; set; }
        public Nullable<decimal> NEC { get; set; }
        public Nullable<decimal> SECONDMENT { get; set; }
        public Nullable<decimal> SPECIAL { get; set; }
        public Nullable<decimal> COLA { get; set; }
        public Nullable<bool> IsOverTimeEligible { get; set; }
        public Nullable<bool> EPFContributionRate { get; set; }
        public Nullable<bool> EPFContribution { get; set; }
        public Nullable<bool> SOCSOContribution { get; set; }
        public Nullable<decimal> KOPERASI { get; set; }
        public Nullable<bool> NubeSubscription { get; set; }
        public Nullable<decimal> GMIS { get; set; }
        public Nullable<decimal> BIMBLoan { get; set; }
        public Nullable<decimal> GELA { get; set; }
        public Nullable<decimal> HomeCarLoans { get; set; }
        public Nullable<decimal> OtherLoans { get; set; }
        public bool PCB { get; set; }
        public bool UnpaidLeave { get; set; }
        public bool IsOtherEligible { get; set; }
        public Nullable<decimal> Others { get; set; }
        public bool RatioOfContribution { get; set; }
        public bool EPF { get; set; }
        public Nullable<bool> SOCSO { get; set; }
        public string ZipCode { get; set; }
        public bool IsResigned { get; set; }
        public string ResignedReason { get; set; }
        public Nullable<System.DateTime> ResignedDate { get; set; }
        public string EPFNumber { get; set; }
        public string SOCSONumber { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<decimal> IncomeTax { get; set; }
        public decimal NoOfCL { get; set; }
        public decimal NoOfML { get; set; }
        public bool IsUserLogin { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public bool IsAdmin { get; set; }
        public int ShiftId { get; set; }
        public Nullable<decimal> MobileAllowance { get; set; }
        public bool IsCancel { get; set; }
        public Nullable<System.DateTime> CancelOn { get; set; }
        public string SIPNumber { get; set; }
        public bool SIP { get; set; }
        public decimal OtherLoanTotal { get; set; }
        public decimal PaidAmount { get; set; }
        public decimal BalanceAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttedanceLog> AttedanceLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendanceCorrection> AttendanceCorrections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyAttedanceDet> DailyAttedanceDets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyLateLog> DailyLateLogs { get; set; }
        public virtual EmployeeShift EmployeeShift { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LatePermissionDetail> LatePermissionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeavePermissionDetail> LeavePermissionDetails { get; set; }
        public virtual MasterBank MasterBank { get; set; }
        public virtual MasterCity MasterCity { get; set; }
        public virtual MasterCountry MasterCountry { get; set; }
        public virtual MasterPosition MasterPosition { get; set; }
        public virtual MasterRace MasterRace { get; set; }
        public virtual MasterNubeBranch MasterNubeBranch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OTClaim> OTClaims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OverTimeDetail> OverTimeDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PCB> PCBs { get; set; }
        public virtual MasterState MasterState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TempAttendanceTiming> TempAttendanceTimings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YearlyAllowance> YearlyAllowances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonthlyDeduction> MonthlyDeductions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonthlySalary> MonthlySalaries { get; set; }
    }
}
