//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUBE.PAYROLL.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlySalary
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public int EmployeeNo { get; set; }
        public Nullable<System.DateTime> SalaryMonth { get; set; }
        public string EmployeeName { get; set; }
        public string EPFNumber { get; set; }
        public string SOCSONumber { get; set; }
        public string NRIC { get; set; }
        public string BankAccountNo { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public Nullable<decimal> TotalWorkingDays { get; set; }
        public Nullable<decimal> DaysAbsent { get; set; }
        public Nullable<decimal> OTHours { get; set; }
        public Nullable<decimal> OT_Amount { get; set; }
        public Nullable<decimal> LOP { get; set; }
        public Nullable<decimal> ALLOWANCE { get; set; }
        public Nullable<decimal> BONUS { get; set; }
        public Nullable<decimal> EXGRATIA { get; set; }
        public Nullable<decimal> EPF { get; set; }
        public Nullable<decimal> EPFUNION { get; set; }
        public Nullable<decimal> SOCSO { get; set; }
        public Nullable<decimal> SOCSOUNION { get; set; }
        public Nullable<decimal> INCOMETAX { get; set; }
        public Nullable<decimal> COOPSOCIETY { get; set; }
        public Nullable<decimal> GMIS { get; set; }
        public Nullable<decimal> GELA { get; set; }
        public Nullable<decimal> LOAN { get; set; }
        public Nullable<decimal> OTHERS { get; set; }
        public Nullable<decimal> KOPERASI { get; set; }
        public Nullable<decimal> NUBESUBSCRIPTION { get; set; }
        public Nullable<decimal> PCB { get; set; }
        public Nullable<decimal> BIMBLOAN { get; set; }
        public Nullable<decimal> HOMECARLOANS { get; set; }
        public Nullable<decimal> OTHERLOANS { get; set; }
        public Nullable<decimal> TOTALEARNING { get; set; }
        public Nullable<decimal> TOTALDEDUCTION { get; set; }
        public Nullable<decimal> NETSALARY { get; set; }
        public string PositionName { get; set; }
    
        public virtual MasterEmployee MasterEmployee { get; set; }
    }
}
