//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUBE.PAYROLL.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTClaim
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<System.DateTime> FromTime { get; set; }
        public Nullable<System.DateTime> ToTime { get; set; }
        public Nullable<decimal> TotalHours { get; set; }
        public bool NormalHours { get; set; }
        public bool RestHalfDay { get; set; }
        public bool RestFullDay { get; set; }
        public bool RestAfter8Hours { get; set; }
        public bool PHoliday8Hours { get; set; }
        public bool PHolidayAfter8Hours { get; set; }
        public bool Meals { get; set; }
    }
}
