//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUBE.PAYROLL.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTClaim
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<System.DateTime> FromTime { get; set; }
        public Nullable<System.DateTime> ToTime { get; set; }
        public string TotalHours { get; set; }
        public string NormalHours { get; set; }
        public string RestHalfDay { get; set; }
        public string RestFullDay { get; set; }
        public string RestAfter8Hours { get; set; }
        public string PHoliday8Hours { get; set; }
        public string PHolidayAfter8Hours { get; set; }
        public string Meals { get; set; }
        public bool IsApproved { get; set; }
        public string Status { get; set; }
    
        public virtual MasterEmployee MasterEmployee { get; set; }
    }
}
