//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUBE.PAYROLL.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPCont
    {
        public int Id { get; set; }
        public Nullable<decimal> MinRM { get; set; }
        public Nullable<decimal> MaxRM { get; set; }
        public Nullable<decimal> Majikan { get; set; }
        public Nullable<decimal> Pekerja { get; set; }
        public Nullable<decimal> Caruman { get; set; }
        public Nullable<decimal> JenisSahaja { get; set; }
        public bool IsCancel { get; set; }
        public Nullable<System.DateTime> CancelOn { get; set; }
    }
}
