//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUBE.PAYROLL.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTypeDetail
    {
        public int Id { get; set; }
        public Nullable<int> UserTypeId { get; set; }
        public Nullable<int> UserTypeFormDetailId { get; set; }
        public Nullable<bool> IsViewForm { get; set; }
        public Nullable<bool> AllowInsert { get; set; }
        public Nullable<bool> AllowUpdate { get; set; }
        public Nullable<bool> AllowDelete { get; set; }
    
        public virtual UserType UserType { get; set; }
        public virtual UserTypeFormDetail UserTypeFormDetail { get; set; }
    }
}
