//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUBE.PAYROLL.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewMasterEmployee
    {
        public Nullable<long> RNO { get; set; }
        public int ID { get; set; }
        public Nullable<int> MEMBERSHIPNO { get; set; }
        public string EMPLOYEENAME { get; set; }
        public string SHORTNAME { get; set; }
        public string NRIC { get; set; }
        public string PositionName { get; set; }
        public string GENDER { get; set; }
    }
}
