//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUBE.PAYROLL.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEWWORKINGDAY
    {
        public int EMPLOYEEID { get; set; }
        public Nullable<int> ATT_MONTH { get; set; }
        public Nullable<int> ATT_YEAR { get; set; }
        public Nullable<decimal> WORKINGDAYS { get; set; }
        public int HALFDAYLEAVE { get; set; }
        public int FULLDAYLEAVE { get; set; }
        public Nullable<int> TOTALLEAVE { get; set; }
        public Nullable<int> PUBLICHOLIDAY { get; set; }
        public Nullable<int> WEEKOFF { get; set; }
        public Nullable<decimal> BASICSALARY { get; set; }
        public Nullable<decimal> ONE_DAY_SALARY { get; set; }
        public Nullable<decimal> LOP { get; set; }
    }
}
