//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUBE.PAYROLL.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEWMONTHLY_WORKINGDAYS
    {
        public int EMPLOYEEID { get; set; }
        public Nullable<int> ATT_MONTH { get; set; }
        public Nullable<int> ATT_YEAR { get; set; }
        public Nullable<int> WORKINGDAYS { get; set; }
    }
}
