//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUBE.PAYROLL.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewEmployeeDetail
    {
        public int ID { get; set; }
        public string EMPLOYEENAME { get; set; }
        public string FATHERNAME { get; set; }
        public string SHORTNAME { get; set; }
        public Nullable<int> MEMBERSHIPNO { get; set; }
        public string GENDER { get; set; }
        public string NRIC { get; set; }
        public Nullable<int> POSITIONID { get; set; }
        public string POSITIONNAME { get; set; }
        public string BLOODGROUP { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string ZIPCODE { get; set; }
        public Nullable<int> CITYID { get; set; }
        public Nullable<int> STATEID { get; set; }
        public Nullable<int> COUNTRYID { get; set; }
        public string MOBILENO { get; set; }
        public string TELEPHONENO { get; set; }
        public string EMAIL { get; set; }
        public string GSTNO { get; set; }
        public Nullable<int> BANKID { get; set; }
        public Nullable<int> NUBEBRANCHID { get; set; }
        public Nullable<System.DateTime> DATEOFBIRTH { get; set; }
        public Nullable<int> RACEID { get; set; }
        public Nullable<System.DateTime> DATEOFJOINING { get; set; }
        public string IDENTYMARK { get; set; }
        public string BANKACCOUNTNO { get; set; }
        public Nullable<decimal> OPENINGBALANCE { get; set; }
        public Nullable<decimal> BASICSALARY { get; set; }
        public Nullable<decimal> POB { get; set; }
        public Nullable<decimal> NEC { get; set; }
        public Nullable<decimal> SECONDMENT { get; set; }
        public Nullable<decimal> SPECIAL { get; set; }
        public Nullable<decimal> COLA { get; set; }
        public Nullable<bool> ISOVERTIMEELIGIBLE { get; set; }
        public Nullable<bool> EPFCONTRIBUTIONRATE { get; set; }
        public Nullable<bool> EPFCONTRIBUTION { get; set; }
        public Nullable<bool> SOCSOCONTRIBUTION { get; set; }
        public Nullable<decimal> KOPERASI { get; set; }
        public Nullable<bool> NUBESUBSCRIPTION { get; set; }
        public Nullable<decimal> GMIS { get; set; }
        public Nullable<decimal> BIMBLOAN { get; set; }
        public Nullable<decimal> GELA { get; set; }
        public Nullable<decimal> HOMECARLOANS { get; set; }
        public Nullable<decimal> PCB { get; set; }
        public Nullable<decimal> UNPAIDLEAVE { get; set; }
        public Nullable<bool> ISOTHERELIGIBLE { get; set; }
        public Nullable<decimal> OTHERS { get; set; }
        public Nullable<bool> RATIOOFCONTRIBUTION { get; set; }
        public Nullable<bool> EPF { get; set; }
        public Nullable<bool> SOCSO { get; set; }
        public Nullable<bool> ISRESIGNED { get; set; }
        public string RESIGNEDREASON { get; set; }
        public Nullable<System.DateTime> RESIGNEDDATE { get; set; }
    }
}
