//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUBE.PAYROLL.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEWEPF_SOCSO
    {
        public int EMPLOYEEID { get; set; }
        public decimal EPF { get; set; }
        public decimal EPFUNION { get; set; }
        public decimal SOCSO { get; set; }
        public decimal SOCSOUNION { get; set; }
    }
}
