//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUBE.PAYROLL.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewOTCalculation
    {
        public int ID { get; set; }
        public Nullable<int> MEMBERSHIPNO { get; set; }
        public Nullable<decimal> BASICSALARY { get; set; }
        public Nullable<decimal> PH { get; set; }
        public Nullable<decimal> OT01 { get; set; }
        public Nullable<decimal> OT02 { get; set; }
        public Nullable<decimal> OT03 { get; set; }
        public Nullable<decimal> OT04 { get; set; }
        public Nullable<decimal> OT05 { get; set; }
        public Nullable<decimal> OT06 { get; set; }
    }
}
