//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUBE.PAYROLL.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEWPAYSLIP
    {
        public Nullable<long> RNO { get; set; }
        public int ID { get; set; }
        public Nullable<int> CODE { get; set; }
        public string EMPLOYEENAME { get; set; }
        public string POSITIONNAME { get; set; }
        public string EPFNUMBER { get; set; }
        public string SOCSONUMBER { get; set; }
        public string NRIC { get; set; }
        public string BANKACCOUNTNO { get; set; }
        public Nullable<decimal> BASICSALARY { get; set; }
        public Nullable<int> TOTALWORKINGDAYS { get; set; }
        public Nullable<int> DAYSABSENT { get; set; }
        public decimal OT { get; set; }
        public Nullable<decimal> OT_AMOUNT { get; set; }
        public Nullable<decimal> LOP { get; set; }
        public Nullable<decimal> ALLOWANCE { get; set; }
        public decimal BONUS { get; set; }
        public decimal EXGRATIA { get; set; }
        public decimal EPF { get; set; }
        public decimal EPFUNION { get; set; }
        public decimal SOCSO { get; set; }
        public decimal SOCSOUNION { get; set; }
        public decimal INCOMETAX { get; set; }
        public Nullable<decimal> COOPSOCIETY { get; set; }
        public Nullable<decimal> GMIS { get; set; }
        public Nullable<decimal> GELA { get; set; }
        public Nullable<decimal> LOAN { get; set; }
        public Nullable<decimal> OTHERS { get; set; }
        public Nullable<decimal> KOPERASI { get; set; }
        public Nullable<decimal> NUBESUBSCRIPTION { get; set; }
        public Nullable<decimal> BIMBLOAN { get; set; }
        public Nullable<decimal> HOMECARLOANS { get; set; }
        public decimal OTHERLOANS { get; set; }
        public Nullable<decimal> TOTALEARNING { get; set; }
        public Nullable<decimal> TOTALDEDUCTION { get; set; }
        public Nullable<decimal> NETSALARY { get; set; }
        public decimal PCB { get; set; }
    }
}
